# -*- coding: utf-8 -*-
{
    "name": "QimamHD Booking V2",
    "summary": "Branch-based event hall and hotel booking platform",
    "version": "13.0.21.0.0",
    "category": "Services",
    "author": "QimamHD",
    "license": "LGPL-3",
    "depends": ["base", "mail", "account", "contacts", "custom_branch_13"],
    "data": [
        "security/booking_security.xml",
        "security/ir.model.access.csv",
        "data/operation_templates.xml",
        "data/booking_sequence.xml",
        "data/booking_period_data.xml",
        "data/booking_cron.xml",
        "data/api_session_cron.xml",
        "data/stay_sequence.xml",
        "views/booking_period_views.xml",
        "views/booking_hall_views.xml",
        "views/booking_service_views.xml",
        "views/booking_package_views.xml",
        "views/booking_views.xml",
        "views/booking_dashboard_views.xml",
        "views/visual_planner_views.xml",
        "views/booking_os_views.xml",
        "views/booking_operations_views.xml",
        "views/booking_studio_views.xml",
        "views/payment_experience_views.xml",
        "views/mission_control_views.xml",
        "views/executive_dashboard_views.xml",
        "views/security_audit_views.xml",
        "views/booking_branch_views.xml",
        "views/booking_migration_views.xml",
        "views/booking_api_session_views.xml",
        "views/booking_confirmation_settings_views.xml",
        "views/booking_resource_views.xml",
        "views/stay_booking_views.xml",
        "views/booking_settings_mode_views.xml",
        "views/booking_demo_settings_views.xml",
        "views/booking_availability_views.xml",
        "views/booking_payment_schedule_views.xml",
        "views/booking_config_views.xml",
        "wizard/booking_quick_wizard_views.xml",
        "wizard/booking_cancel_wizard_views.xml",
        "wizard/booking_invoice_wizard_views.xml",
        "wizard/booking_payment_schedule_wizard_views.xml",
        "wizard/booking_reversal_wizard_views.xml",
        "wizard/stay_financial_wizard_views.xml",
        "views/booking_menu.xml"
    ],
    "application": True,
    "installable": True,
    "qweb": ["static/src/xml/visual_planners.xml", "static/src/xml/booking_os.xml", "static/src/xml/booking_operations.xml", "static/src/xml/booking_studio.xml", "static/src/xml/payment_experience.xml", "static/src/xml/mission_control.xml", "static/src/xml/executive_dashboard.xml"],
}
